import type { QuestionSet } from './model';

/**
 * オシハピ｜推し買い診断（merch_v2_ja）
 * - 通常：Core 12問
 * - 急ぎ：6問
 * - 長診断：Core 12 + itemType別追加4問
 *
 * Note: ここでは「チケット」も itemKind= ticket として同枠で扱う（周辺グッズの一種）。
 */
export const merch_v2_ja: QuestionSet = {
  id: 'merch_v2_ja',
  locale: 'ja',
  category: 'merch',
  version: 2,
  questions: [
    {
      id: 'q_desire',
      type: 'scale',
      title: 'これは「推し度（欲しさ）」どれくらい？',
      description: '0=気になるだけ / 5=本命レベル',
      required: true,
      urgentCore: true,
      standard: true,
      min: 0,
      max: 5,
      step: 1,
      defaultValue: 3,
      mapTo: 'desire',
      leftLabel: '気になるだけ',
      rightLabel: '本命',
    },
    {
      id: 'q_storage_fit',
      type: 'single',
      title: '置き場所、決まってる？',
      required: true,
      options: [
        { id: 'CONFIRMED', label: 'ある（もう決まってる）' },
        { id: 'PROBABLE', label: 'たぶんある（片付ければ）' },
        { id: 'NONE', label: '今はない' },
        { id: 'UNKNOWN', label: 'わからない（先に確認する）' },
      ],
    },

    {
      id: 'q_budget_pain',
      type: 'single',
      title: 'この出費、あとで痛い？',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'ok', label: '全然平気', tags: ['budget_ok'], delta: { affordability: 85, regretRisk: 35 } },
        { id: 'some', label: 'ちょい痛い', tags: ['budget_some'], delta: { affordability: 60, regretRisk: 45 } },
        { id: 'hard', label: '生活に影響する', tags: ['budget_hard'], delta: { affordability: 35, regretRisk: 65 } },
        { id: 'force', label: '無理して払う（危険）', tags: ['budget_force'], delta: { affordability: 15, regretRisk: 80, impulse: 70 } },
      ],
    },
    {
      id: 'q_urgency',
      type: 'single',
      title: '今買わないとどうなる？（急ぎ度）',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'not_urgent', label: 'いつでも買えそう', tags: ['urgency_low'], delta: { urgency: 20, rarity: 30, restockChance: 70 } },
        { id: 'low_stock', label: '在庫が減ってる/締切が近い', tags: ['urgency_mid'], delta: { urgency: 55, rarity: 55, restockChance: 45 } },
        { id: 'last', label: 'ほぼラスト/今日が期限', tags: ['urgency_high'], delta: { urgency: 85, rarity: 70, restockChance: 25 } },
        { id: 'unknown', label: 'わからない', tags: ['unknown_urgency'], delta: { urgency: 50 } },
      ],
    },
    {
      id: 'q_rarity_restock',
      type: 'single',
      title: '再販（受注/再入荷）しそう？',
      description: '再販が高いほど「今買う必要」は下がりやすい',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'likely', label: 'しそう（高い）', tags: ['restock_high'], delta: { restockChance: 80, rarity: 35 } },
        { id: 'maybe', label: 'たぶん（中）', tags: ['restock_mid'], delta: { restockChance: 55, rarity: 50 } },
        { id: 'unlikely', label: 'しなさそう（低い）', tags: ['restock_low'], delta: { restockChance: 25, rarity: 75 } },
        { id: 'unknown', label: 'わからない', tags: ['unknown_restock'], delta: { restockChance: 50, rarity: 50 } },
      ],
    },
    {
      id: 'q_goal',
      type: 'single',
      title: '今回の買い方（回収スタイル）、どれが近い？',
      description: '買い方提案（中古/BOX/くじ上限）に影響する',
      required: true,
      urgentCore: false,
      standard: true,
      options: [
        { id: 'single', label: '本命だけ確実に（1点狙い）', tags: ['goal_single'] },
        { id: 'set', label: 'まとめて揃えたい（セット/複数買い）', tags: ['goal_set'] },
        { id: 'fun', label: '買う過程も楽しみたい（現場/開封/抽選など）', tags: ['goal_fun'] },
        { id: 'unknown', label: '該当なし／まだわからない', tags: ['goal_unknown'] },
      ],
    },
    {
      id: 'q_motives_multi',
      type: 'multi',
      title: '今「買いたい理由」ってどれ？（当てはまるだけ選んでOK／迷ったら1〜3個でもOK）',
      description: '当てはまるものをいくつでも選択OK。',
      required: true,
      urgentCore: false,
      standard: true,
      options: [
        { id: 'rush', label: '買えた瞬間の高揚感がほしい（脳汁）' },
        { id: 'support', label: '推しを応援したい（気持ち）' },
        { id: 'use', label: '飾りたい／使いたい（未来がある）' },
        { id: 'fomo', label: '限定・締切が怖い（取り逃し不安）' },
        { id: 'bonus', label: '特典が本体（特典目的）' },
        { id: 'trend', label: 'みんな買ってる／流行ってる（雰囲気）' },
        { id: 'vague', label: 'なんとなく（説明できない）' },
        { id: 'memory', label: '記念・思い出として残したい' },
        { id: 'content', label: '中身（絵/文章/デザイン）が好き' },
        { id: 'complete', label: '揃えたい／コンプしたい' },
        { id: 'display', label: '飾って眺めたい' },
        { id: 'archive', label: '手元に保存・アーカイブしたい' },
        { id: 'reward', label: '自分へのご褒美' },
        { id: 'scarce', label: '今逃すと後悔しそう（再入手が難しそう）' },
        { id: 'price_up', label: 'あとで高くなりそう（相場/プレ値）' },
        { id: 'habit', label: '習慣でつい買ってしまう（ルーティン）' },
      ],
    },
    {
      id: 'q_hot_cold',
      type: 'single',
      title: '欲しい枠（推し）は人気枠？（高レート/低レート）',
      required: true,
      urgentCore: false,
      standard: true,
      options: [
        { id: 'hot', label: '人気（高騰/プレ値になりやすい）', tags: ['hot'] },
        { id: 'normal', label: '普通', tags: ['normal_popularity'] },
        { id: 'cold', label: '落ち着いてる（低レートになりやすい）', tags: ['cold'] },
        { id: 'unknown', label: 'わからない', tags: ['unknown_popularity'] },
      ],
    },
    {
      id: 'q_price_feel',
      type: 'single',
      title: '価格の納得感は？',
      required: true,
      options: [
        { id: 'good', label: '納得できる' },
        { id: 'normal', label: '普通' },
        { id: 'high', label: '高めに感じる' },
        { id: 'unknown', label: 'まだ比較できていない' },
      ],
    },
    {
      id: 'q_storage_space',
      type: 'single',
      title: '置き場所・保管の見通しは？',
      required: true,
      options: [
        { id: 'enough', label: '問題ない' },
        { id: 'adjust', label: '少し工夫が必要' },
        { id: 'tight', label: 'かなり厳しい' },
      ],
    },
    {
      id: 'q_alternative_plan',
      type: 'single',
      title: '見送る場合の代替案はある？',
      required: true,
      options: [
        { id: 'clear', label: 'ある（他の満たし方がある）' },
        { id: 'maybe', label: 'たぶんある' },
        { id: 'none', label: '特にない' },
      ],
    },
    {
      id: 'q_impulse_axis_short',
      type: 'single',
      title: '今の気持ち、どれに近い？',
      description: '直感でOK。30秒で終わるやつ。',
      required: true,
      urgentCore: false,
      standard: false,
      shortOnly: true,
      options: [
        { id: 'plan', label: '見返す/保管までイメージできてる（計画型）' },
        { id: 'mood', label: '今のテンションで欲しい（計画はまだ）' },
        { id: 'both', label: '両方ある（計画もあるし、今も高まってる）' },
        { id: 'unknown', label: 'まだわからない' },
      ],
    },
    {
      id: 'q_regret_impulse',
      type: 'single',
      title: 'いまの自分、どれに近い？（衝動/後悔リスク）',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'calm', label: '冷静（後悔しにくい）', tags: ['state_calm'], delta: { impulse: 25, regretRisk: 35 } },
        { id: 'excited', label: 'テンション高め（勢い）', tags: ['state_excited'], delta: { impulse: 65, regretRisk: 55 } },
        { id: 'tired', label: '疲れてる/メンタル弱り気味', tags: ['state_tired'], delta: { impulse: 70, regretRisk: 70 } },
        { id: 'fomo', label: '焦ってる（今しかない圧）', tags: ['state_fomo'], delta: { impulse: 75, regretRisk: 65, urgency: 70 } },
      ],
    },
    {
      id: 'q_long_note',
      type: 'text',
      title: 'AIに相談したいポイントを一言で書いてください',
      description: 'あとでAIに相談するためのメモになります',
      required: false,
      urgentCore: false,
      standard: false,
      longOnly: true,
    },

    {
      id: 'q_addon_common_info',
      type: 'single',
      title: '必要情報は揃っている？',
      required: true,
      options: [
        { id: 'enough', label: '十分そろっている' },
        { id: 'partial', label: '一部足りない' },
        { id: 'lack', label: '不足が多い' },
      ],
    },
    {
      id: 'q_addon_common_priority',
      type: 'single',
      title: '今月の推し活の中で優先度は？',
      required: true,
      options: [
        { id: 'high', label: '高い' },
        { id: 'mid', label: '中くらい' },
        { id: 'low', label: '低め' },
      ],
    },
    {
      id: 'q_addon_goods_compare',
      type: 'single',
      title: '同系統アイテムとの比較はできた？',
      required: true,
      options: [
        { id: 'done', label: '比較済み' },
        { id: 'partial', label: '一部だけ比較した' },
        { id: 'none', label: 'まだ比較していない' },
      ],
    },
    {
      id: 'q_addon_goods_portability',
      type: 'single',
      title: '持ち歩き・使いどころの想定は？',
      required: true,
      options: [
        { id: 'often', label: 'よく使う想定' },
        { id: 'sometimes', label: '時々使う想定' },
        { id: 'rare', label: 'ほぼ観賞用' },
      ],
    },
    {
      id: 'q_addon_goods_collection_goal',
      type: 'single',
      title: '収集の目的は？',
      required: true,
      options: [
        { id: 'oshi_expression', label: '推し表現したい' },
        { id: 'complete_set', label: '揃えたい' },
        { id: 'single_enough', label: '1個で満足' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_duplicate_tolerance',
      type: 'single',
      title: '被り許容は？',
      required: true,
      options: [
        { id: 'ok', label: 'OK' },
        { id: 'slightly_dislike', label: '少し嫌' },
        { id: 'no', label: '絶対嫌' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_paper_care',
      type: 'single',
      title: '紙もの、どう保管する？',
      required: true,
      options: [
        { id: 'file', label: 'ファイル保管' },
        { id: 'scan', label: 'スキャンする' },
        { id: 'rough', label: '適当に保管' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_paper_view_freq',
      type: 'single',
      title: '見返す頻度は？',
      required: true,
      options: [
        { id: 'often', label: 'よく見る' },
        { id: 'sometimes', label: 'たまに見る' },
        { id: 'rare', label: 'ほぼ見ない' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_wear_freq',
      type: 'single',
      title: '使う頻度は？',
      required: true,
      options: [
        { id: 'high', label: '高い' },
        { id: 'mid', label: '中' },
        { id: 'low', label: '低い' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_wear_fit',
      type: 'single',
      title: 'サイズ・雰囲気の相性は？',
      required: true,
      options: [
        { id: 'confident', label: '自信ある' },
        { id: 'iffy', label: '微妙' },
        { id: 'anxious', label: '不安' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_display_space_plan',
      type: 'single',
      title: '置き場計画はある？',
      required: true,
      options: [
        { id: 'yes', label: 'ある' },
        { id: 'rough', label: 'だいたいある' },
        { id: 'none', label: 'ない' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_display_move_risk',
      type: 'single',
      title: '搬送・破損リスクは？',
      required: true,
      options: [
        { id: 'dont_mind', label: '気にしない' },
        { id: 'some', label: '少し気にする' },
        { id: 'high', label: '強く気にする' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_tech_compat',
      type: 'single',
      title: '互換確認はした？',
      required: true,
      options: [
        { id: 'checked', label: '確認済み' },
        { id: 'maybe', label: 'たぶん大丈夫' },
        { id: 'unchecked', label: '未確認' },
        { id: 'unknown', label: 'わからない' },
      ],
    },
    {
      id: 'q_addon_goods_tech_after_use',
      type: 'single',
      title: '現場後も使う？',
      required: true,
      options: [
        { id: 'use', label: '使う' },
        { id: 'maybe', label: 'たぶん使う' },
        { id: 'not_use', label: '使わない' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_goods_itabag_target',
      type: 'single',
      title: '目標個数/完成イメージは？',
      required: true,
      options: [
        { id: 'concrete', label: '具体的にある' },
        { id: 'rough', label: 'だいたいある' },
        { id: 'unknown', label: '未定' },
      ],
    },
    {
      id: 'q_addon_blind_draw_cap',
      type: 'single',
      title: 'くじ・ブラインドの回数上限は決めた？',
      required: true,
      options: [
        { id: 'fixed', label: '決めた' },
        { id: 'rough', label: 'だいたい決めた' },
        { id: 'none', label: 'まだ決めていない' },
      ],
    },
    {
      id: 'q_addon_blind_draw_exit',
      type: 'single',
      title: '撤退ライン（やめどき）はある？',
      required: true,
      options: [
        { id: 'clear', label: '明確にある' },
        { id: 'some', label: 'なんとなくある' },
        { id: 'none', label: '特にない' },
      ],
    },
    {
      id: 'q_addon_ticket_schedule',
      type: 'single',
      title: '日程・移動・体調まで見通せている？',
      required: true,
      options: [
        { id: 'ready', label: '問題なし' },
        { id: 'some_risk', label: '少し不安あり' },
        { id: 'risk', label: '不確定が多い' },
      ],
    },
    {
      id: 'q_addon_ticket_resale_rule',
      type: 'single',
      title: 'キャンセル・譲渡ルールを確認した？',
      required: true,
      options: [
        { id: 'checked', label: '確認済み' },
        { id: 'partly', label: '一部だけ確認' },
        { id: 'not_yet', label: '未確認' },
      ],
    },
    {
      id: 'q_addon_preorder_timeline',
      type: 'single',
      title: '発売・到着タイミングを許容できる？',
      required: true,
      options: [
        { id: 'ok', label: '待てる' },
        { id: 'maybe', label: '状況次第' },
        { id: 'hard', label: '待つのが厳しい' },
      ],
    },
    {
      id: 'q_addon_preorder_restock',
      type: 'single',
      title: '受注再開・再販の可能性を確認した？',
      required: true,
      options: [
        { id: 'checked', label: '確認した' },
        { id: 'heard', label: '噂レベルで知っている' },
        { id: 'unknown', label: 'わからない' },
      ],
    },
    {
      id: 'q_addon_used_condition',
      type: 'single',
      title: '中古の状態リスクを許容できる？',
      required: true,
      options: [
        { id: 'ok', label: '許容できる' },
        { id: 'careful', label: '条件次第' },
        { id: 'hard', label: '不安が大きい' },
      ],
    },
    {
      id: 'q_addon_used_price_gap',
      type: 'single',
      title: '新品との差額は納得できる？',
      required: true,
      options: [
        { id: 'worth', label: '納得できる' },
        { id: 'small', label: '差額が小さい' },
        { id: 'unknown', label: '比較できていない' },
      ],
    },
  ],
};
