import type { QuestionSet } from './model';

/**
 * オシハピ｜推し買い診断（merch_v2_ja）
 * - 通常：Core 12問
 * - 急ぎ：6問
 * - 長診断：Core 12 + itemType別追加4問
 *
 * Note: ここでは「チケット」も itemKind= ticket として同枠で扱う（周辺グッズの一種）。
 */
export const merch_v2_ja: QuestionSet = {
  id: 'merch_v2_ja',
  locale: 'ja',
  category: 'merch',
  version: 2,
  questions: [
    {
      id: 'q_desire',
      type: 'scale',
      title: 'これは「推し度（欲しさ）」どれくらい？',
      description: '0=気になるだけ / 5=本命レベル',
      required: true,
      urgentCore: true,
      standard: true,
      min: 0,
      max: 5,
      step: 1,
      defaultValue: 3,
      mapTo: 'desire',
      leftLabel: '気になるだけ',
      rightLabel: '本命',
    },
    {
      id: 'q_storage_fit',
      type: 'single',
      title: '保管プラン（ファイル/スキャン/置き場所）は決まってる？',
      required: true,
      options: [
        { id: 'CONFIRMED', label: 'ある（もう決まってる）' },
        { id: 'PROBABLE', label: 'たぶんある（片付ければ）' },
        { id: 'NONE', label: '今はない' },
        { id: 'UNKNOWN', label: 'わからない（先に確認する）' },
      ],
    },

    {
      id: 'q_budget_pain',
      type: 'single',
      title: 'この出費、あとで痛い？',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'ok', label: '全然平気', tags: ['budget_ok'], delta: { affordability: 85, regretRisk: 35 } },
        { id: 'some', label: 'ちょい痛い', tags: ['budget_some'], delta: { affordability: 60, regretRisk: 45 } },
        { id: 'hard', label: '生活に影響する', tags: ['budget_hard'], delta: { affordability: 35, regretRisk: 65 } },
        { id: 'force', label: '無理して払う（危険）', tags: ['budget_force'], delta: { affordability: 15, regretRisk: 80, impulse: 70 } },
      ],
    },
    {
      id: 'q_urgency',
      type: 'single',
      title: '今買わないとどうなる？（急ぎ度）',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'not_urgent', label: 'いつでも買えそう', tags: ['urgency_low'], delta: { urgency: 20, rarity: 30, restockChance: 70 } },
        { id: 'low_stock', label: '在庫が減ってる/締切が近い', tags: ['urgency_mid'], delta: { urgency: 55, rarity: 55, restockChance: 45 } },
        { id: 'last', label: 'ほぼラスト/今日が期限', tags: ['urgency_high'], delta: { urgency: 85, rarity: 70, restockChance: 25 } },
        { id: 'unknown', label: 'わからない', tags: ['unknown_urgency'], delta: { urgency: 50 } },
      ],
    },
    {
      id: 'q_rarity_restock',
      type: 'single',
      title: '再販（受注/再入荷）しそう？',
      description: '再販が高いほど「今買う必要」は下がりやすい',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'likely', label: 'しそう（高い）', tags: ['restock_high'], delta: { restockChance: 80, rarity: 35 } },
        { id: 'maybe', label: 'たぶん（中）', tags: ['restock_mid'], delta: { restockChance: 55, rarity: 50 } },
        { id: 'unlikely', label: 'しなさそう（低い）', tags: ['restock_low'], delta: { restockChance: 25, rarity: 75 } },
        { id: 'unknown', label: 'わからない', tags: ['unknown_restock'], delta: { restockChance: 50, rarity: 50 } },
      ],
    },
    {
      id: 'q_goal',
      type: 'single',
      title: '今回の買い方（回収スタイル）、どれが近い？',
      description: '買い方提案（中古/BOX/くじ上限）に影響する',
      required: true,
      urgentCore: false,
      standard: true,
      options: [
        { id: 'single', label: '本命だけ確実に（1点狙い）', tags: ['goal_single'] },
        { id: 'set', label: 'まとめて揃えたい（セット/複数買い）', tags: ['goal_set'] },
        { id: 'fun', label: '買う過程も楽しみたい（現場/開封/抽選など）', tags: ['goal_fun'] },
        { id: 'unknown', label: '該当なし／まだわからない', tags: ['goal_unknown'] },
      ],
    },
    {
      id: 'q_motives_multi',
      type: 'multi',
      title: '今「買いたい理由」ってどれ？（当てはまるだけ選んでOK／迷ったら1〜3個でもOK）',
      description: '当てはまるものをいくつでも選択OK。',
      required: true,
      urgentCore: false,
      standard: true,
      options: [
        { id: 'rush', label: '買えた瞬間の高揚感がほしい（脳汁）' },
        { id: 'support', label: '推しを応援したい（気持ち）' },
        { id: 'use', label: '飾りたい／使いたい（未来がある）' },
        { id: 'fomo', label: '限定・締切が怖い（取り逃し不安）' },
        { id: 'bonus', label: '特典が本体（特典目的）' },
        { id: 'trend', label: 'みんな買ってる／流行ってる（雰囲気）' },
        { id: 'vague', label: 'なんとなく（説明できない）' },
        { id: 'memory', label: '記念・思い出として残したい' },
        { id: 'content', label: '中身（絵/文章/デザイン）が好き' },
        { id: 'complete', label: '揃えたい／コンプしたい' },
        { id: 'display', label: '飾って眺めたい' },
        { id: 'archive', label: '手元に保存・アーカイブしたい' },
        { id: 'reward', label: '自分へのご褒美' },
        { id: 'scarce', label: '今逃すと後悔しそう（再入手が難しそう）' },
        { id: 'price_up', label: 'あとで高くなりそう（相場/プレ値）' },
        { id: 'habit', label: '習慣でつい買ってしまう（ルーティン）' },
        { id: 'seiyuu_cast', label: '推し声優・演者の参加が決め手' },
      ],
    },
    {
      id: 'q_hot_cold',
      type: 'single',
      title: 'このアイテム、あとで高くなりやすい？（相場/プレ値）',
      required: true,
      urgentCore: false,
      standard: true,
      options: [
        { id: 'hot', label: '高騰しやすい（プレ値になりやすい）', tags: ['hot'] },
        { id: 'normal', label: '普通（大きくは動かなそう）', tags: ['normal_popularity'] },
        { id: 'cold', label: '落ち着いてる（上がりにくい/安定しそう）', tags: ['cold'] },
        { id: 'unknown', label: 'わからない（相場未確認）', tags: ['unknown_popularity'] },
      ],
    },
    {
      id: 'q_price_feel',
      type: 'single',
      title: '価格の納得感は？',
      required: true,
      options: [
        { id: 'good', label: '納得できる', delta: { affordability: 80, regretRisk: 40 } },
        { id: 'normal', label: '普通', delta: { affordability: 60, regretRisk: 50 } },
        { id: 'high', label: '高めに感じる', delta: { affordability: 35, regretRisk: 70, opportunityCost: 65 } },
        { id: 'unknown', label: 'まだ比較できていない', tags: ['unknown_price'], delta: { affordability: 50, regretRisk: 55 } },
      ],
    },
    {
      id: 'q_storage_space',
      type: 'single',
      title: '置き場所・保管の見通しは？',
      required: true,
      options: [
        { id: 'enough', label: '問題ない', delta: { opportunityCost: 30, regretRisk: 35 } },
        { id: 'adjust', label: '少し工夫が必要', delta: { opportunityCost: 55, regretRisk: 50 } },
        { id: 'tight', label: 'かなり厳しい', tags: ['unknown_storage'], delta: { opportunityCost: 80, regretRisk: 70 } },
      ],
    },
    {
      id: 'q_alternative_plan',
      type: 'single',
      title: '見送る場合の代替案はある？',
      required: true,
      options: [
        { id: 'clear', label: 'ある（他の満たし方がある）' },
        { id: 'maybe', label: 'たぶんある' },
        { id: 'none', label: '特にない' },
      ],
    },
    {
      id: 'q_impulse_axis_short',
      type: 'scale',
      title: '今の気持ち、どれに近い？',
      description: '0=計画型 / 5=今のテンション寄り',
      required: true,
      urgentCore: false,
      standard: false,
      shortOnly: true,
      min: 0,
      max: 5,
      step: 1,
      defaultValue: 3,
      mapTo: 'impulse',
      leftLabel: '計画型',
      rightLabel: '気分で買いたい',
    },
    {
      id: 'q_regret_impulse',
      type: 'single',
      title: 'いまの自分、どれに近い？（衝動/後悔リスク）',
      required: true,
      urgentCore: true,
      standard: true,
      options: [
        { id: 'calm', label: '冷静（後悔しにくい）', tags: ['state_calm'], delta: { impulse: 25, regretRisk: 35 } },
        { id: 'excited', label: 'テンション高め（勢い）', tags: ['state_excited'], delta: { impulse: 65, regretRisk: 55 } },
        { id: 'tired', label: '疲れてる/メンタル弱り気味', tags: ['state_tired'], delta: { impulse: 70, regretRisk: 70 } },
        { id: 'fomo', label: '焦ってる（今しかない圧）', tags: ['state_fomo'], delta: { impulse: 75, regretRisk: 65, urgency: 70 } },
      ],
    },
    {
      id: 'q_long_note',
      type: 'text',
      title: 'AIに相談したいポイントを一言で書いてください',
      description: 'あとでAIに相談するためのメモになります',
      required: false,
      urgentCore: false,
      standard: false,
      longOnly: true,
    },

    {
      id: 'q_addon_goods_event_limit_context',
      type: 'single',
      title: '今回の迷い、会場限定・イベント限定グッズの文脈に近い？',
      description: '現地でしか買えない圧なのか、後日回復できそうかを見ます',
      required: true,
      options: [
        { id: 'venue_limited', label: '会場限定っぽく、今その場で迷っている', tags: ['venue_limited_goods'], delta: { urgency: 74, rarity: 72, restockChance: 30 } },
        { id: 'event_limited', label: 'イベント限定寄りだが、後日販売の可能性もありそう', tags: ['event_limited_goods'], delta: { urgency: 62, rarity: 58, restockChance: 44 } },
        { id: 'missed_onsite', label: '現地では逃した/買えなかったので回復策を考えたい', tags: ['missed_onsite_goods'], delta: { urgency: 58, rarity: 60, restockChance: 46 } },
        { id: 'none', label: 'この文脈ではない', delta: { urgency: 45, rarity: 45, restockChance: 55 } },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_event_limit'], delta: { urgency: 52, rarity: 52, restockChance: 50 } },
      ],
    },
    {
      id: 'q_addon_goods_post_event_mailorder',
      type: 'single',
      title: '事後通販・後日オンライン販売はありそう？',
      required: true,
      options: [
        { id: 'likely', label: 'ありそう/例年ある/告知が近そう', tags: ['post_event_recovery_high'], delta: { restockChance: 82, rarity: 34, urgency: 34 } },
        { id: 'maybe', label: 'あるかも/まだ断言できない', tags: ['post_event_recovery_mid'], delta: { restockChance: 62, rarity: 46, urgency: 46 } },
        { id: 'unlikely', label: 'なさそう/根拠が弱い', tags: ['post_event_recovery_low'], delta: { restockChance: 24, rarity: 74, urgency: 70 } },
        { id: 'unknown', label: 'わからない', tags: ['unknown_post_event_recovery'], delta: { restockChance: 50, rarity: 50 } },
      ],
    },
    {
      id: 'q_addon_goods_wait_tolerance',
      type: 'single',
      title: '後日回復を待つのはどれくらい平気？',
      required: true,
      options: [
        { id: 'high', label: 'かなり待てる', tags: ['wait_tolerance_high'], delta: { impulse: 34, regretRisk: 42, urgency: 34 } },
        { id: 'medium', label: '少しなら待てる', tags: ['wait_tolerance_mid'], delta: { impulse: 46, regretRisk: 50, urgency: 46 } },
        { id: 'low', label: '待つのはかなりつらい', tags: ['wait_tolerance_low'], delta: { impulse: 66, regretRisk: 62, urgency: 68 } },
      ],
    },
    {
      id: 'q_addon_goods_first_chance_tolerance',
      type: 'single',
      title: '「最初のチャンス」を逃すことへの耐性は？',
      required: true,
      options: [
        { id: 'high', label: '逃してもあとで整えば大丈夫', tags: ['first_chance_tolerance_high'], delta: { regretRisk: 42, urgency: 36 } },
        { id: 'medium', label: '少し惜しいが許容できる', tags: ['first_chance_tolerance_mid'], delta: { regretRisk: 52, urgency: 50 } },
        { id: 'low', label: '最初の機会を逃すのはかなりつらい', tags: ['first_chance_tolerance_low'], delta: { regretRisk: 68, urgency: 72 } },
      ],
    },
    {
      id: 'q_addon_goods_used_fallback',
      type: 'single',
      title: 'もし逃したら、あとで中古・フリマで回復するのはあり？',
      required: true,
      options: [
        { id: 'high', label: '積極的にあり', tags: ['used_fallback_high'], delta: { restockChance: 70, rarity: 38, regretRisk: 46 } },
        { id: 'medium', label: '条件次第であり', tags: ['used_fallback_mid'], delta: { restockChance: 60, rarity: 48, regretRisk: 52 } },
        { id: 'low', label: 'できれば避けたい', tags: ['used_fallback_low'], delta: { restockChance: 34, rarity: 66, regretRisk: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_scarcity_pressure',
      type: 'single',
      title: '今の scarcity 圧、どれくらい強い？',
      description: '雰囲気ではなく、現地での焦りの強さを自己申告で見ます',
      required: true,
      options: [
        { id: 'low', label: 'そこまで強くない', tags: ['scarcity_pressure_low'], delta: { impulse: 36, urgency: 40 } },
        { id: 'medium', label: 'やや強い', tags: ['scarcity_pressure_mid'], delta: { impulse: 54, urgency: 56 } },
        { id: 'high', label: 'かなり強い/FOMO が大きい', tags: ['scarcity_pressure_high'], delta: { impulse: 78, urgency: 76, regretRisk: 66 } },
      ],
    },
    {
      id: 'q_addon_goods_venue_motive',
      type: 'single',
      title: 'このアイテムが欲しい理由、いちばん近いのは？',
      required: true,
      options: [
        { id: 'collection_completeness', label: 'コレクションの穴を埋めたい/揃えたい', tags: ['collection_pressure'], delta: { desire: 66, impulse: 68, opportunityCost: 62 } },
        { id: 'event_memory', label: 'そのイベントの記念・思い出として残したい', tags: ['event_memory_motive'], delta: { desire: 72, regretRisk: 58 } },
        { id: 'practical_collecting', label: '普通に手元に欲しい/飾りたい', tags: ['practical_collecting_motive'], delta: { desire: 64, regretRisk: 46 } },
        { id: 'mixed', label: 'どれも少しずつある', delta: { desire: 60, regretRisk: 54, impulse: 56 } },
      ],
    },
    {
      id: 'q_addon_goods_live_goods_motive',
      type: 'single',
      title: 'この live / 会場グッズ、イベントの空気だけでなく後からも意味が残りそう？',
      required: true,
      options: [
        { id: 'core_attachment', label: 'キャスト/作品への愛着が強く、後から見ても意味がある', delta: { desire: 68, regretRisk: 46 } },
        { id: 'symbolic_value', label: '1点だけなら記念品として納得できる', delta: { desire: 58, regretRisk: 50 } },
        { id: 'event_atmosphere', label: 'その場の空気で欲しくなっている面が大きい', tags: ['live_goods_atmosphere_pressure'], delta: { impulse: 70, regretRisk: 72 } },
        { id: 'mixed', label: '両方ある', delta: { desire: 60, regretRisk: 58 } },
        { id: 'unknown', label: 'まだ整理できていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_regret_axis',
      type: 'single',
      title: 'どちらの後悔がより重い？',
      required: true,
      options: [
        { id: 'overpay_more', label: '高く掴む/焦って買う後悔の方が重い', tags: ['regret_overpay_more'], delta: { regretRisk: 66, impulse: 42, opportunityCost: 68 } },
        { id: 'balanced', label: 'どちらも同じくらい', tags: ['regret_balanced'], delta: { regretRisk: 56 } },
        { id: 'miss_more', label: '逃して二度と回収できない後悔の方が重い', tags: ['regret_miss_more'], delta: { regretRisk: 62, urgency: 68, rarity: 64 } },
      ],
    },
    {
      id: 'q_addon_common_info',
      type: 'single',
      title: '必要情報は揃っている？',
      required: true,
      options: [
        { id: 'enough', label: '十分そろっている', delta: { regretRisk: 35, opportunityCost: 40 } },
        { id: 'partial', label: '一部足りない', tags: ['unknown_info'], delta: { regretRisk: 55, opportunityCost: 55 } },
        { id: 'lack', label: '不足が多い', tags: ['unknown_info', 'unknown_compare'], delta: { regretRisk: 75, opportunityCost: 75 } },
      ],
    },
    {
      id: 'q_addon_common_priority',
      type: 'single',
      title: '今月の推し活の中で優先度は？',
      required: true,
      options: [
        { id: 'high', label: '高い', delta: { desire: 75, opportunityCost: 35 } },
        { id: 'mid', label: '中くらい', delta: { desire: 55, opportunityCost: 50 } },
        { id: 'low', label: '低め', delta: { desire: 40, opportunityCost: 70 } },
      ],
    },
    {
      id: 'q_addon_goods_compare',
      type: 'single',
      title: '同系統アイテムとの比較はできた？',
      required: true,
      options: [
        { id: 'done', label: '比較済み' },
        { id: 'partial', label: '一部だけ比較した' },
        { id: 'none', label: 'まだ比較していない' },
      ],
    },
    {
      id: 'q_addon_goods_portability',
      type: 'single',
      title: '持ち帰り時の折れ・濡れ対策は？',
      required: true,
      options: [
        { id: 'often', label: 'よく使う想定' },
        { id: 'sometimes', label: '時々使う想定' },
        { id: 'rare', label: 'ほぼ観賞用' },
      ],
    },
    {
      id: 'q_addon_goods_collection_goal',
      type: 'single',
      title: '揃わないと落ち着かない気持ちはありますか？',
      required: true,
      options: [
        { id: 'complete_tolerant', label: 'コンプ寄り・被りも許容できる' },
        { id: 'complete_strict', label: 'コンプ寄り・被りはつらい' },
        { id: 'oshi_tolerant', label: '本命中心・被りは許容できる' },
        { id: 'oshi_strict', label: '本命中心・被りは避けたい' },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_trade_intent',
      type: 'single',
      title: '交換・トレードする意欲は？（任意）',
      required: true,
      options: [
        { id: 'active', label: '積極的に交換したい' },
        { id: 'maybe', label: '条件が合えば交換したい' },
        { id: 'no', label: '交換はしない予定' },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_paper_care',
      type: 'single',
      title: '紙もの、どう保管する？（折れ・湿気対策）',
      required: true,
      options: [
        { id: 'file', label: 'スリーブ＋ファイルで保管', delta: { regretRisk: 35, opportunityCost: 45 } },
        { id: 'scan', label: 'スキャン保存も併用する', delta: { regretRisk: 40, opportunityCost: 45 } },
        { id: 'rough', label: 'まとめ置き/簡易保管になりそう', delta: { regretRisk: 75, opportunityCost: 70 } },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 68, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_paper_view_freq',
      type: 'single',
      title: '見返す頻度は？',
      required: true,
      options: [
        { id: 'often', label: '週1以上で見返す', delta: { desire: 68, regretRisk: 42 } },
        { id: 'sometimes', label: '月1くらいで見返す', delta: { desire: 58, regretRisk: 52 } },
        { id: 'rare', label: 'ほぼ見返さないかも', delta: { desire: 42, regretRisk: 68, opportunityCost: 65 } },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_wear_freq',
      type: 'single',
      title: '使う頻度は？',
      required: true,
      options: [
        { id: 'high', label: '高い' },
        { id: 'mid', label: '中' },
        { id: 'low', label: '低い' },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_wear_fit',
      type: 'single',
      title: 'サイズ感・着用フィットは？',
      required: true,
      options: [
        { id: 'confident', label: '自信ある' },
        { id: 'iffy', label: '微妙' },
        { id: 'anxious', label: '不安' },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_wear_scene',
      type: 'single',
      title: '主な使用シーンは？',
      required: true,
      options: [
        { id: 'live_only', label: 'ライブ/現場中心' },
        { id: 'daily', label: '普段使い中心' },
        { id: 'both', label: '両方で使いたい' },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_display_space_plan',
      type: 'single',
      title: '保管場所と配送/搬入経路の見通しは？',
      required: true,
      options: [
        { id: 'yes', label: 'ある' },
        { id: 'rough', label: 'だいたいある' },
        { id: 'none', label: 'ない' },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_display_move_risk',
      type: 'single',
      title: '配送・搬送や掃除/手入れの負担は？',
      required: true,
      options: [
        { id: 'dont_mind', label: '気にしない' },
        { id: 'some', label: '少し気にする' },
        { id: 'high', label: '強く気にする' },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_tech_compat',
      type: 'single',
      title: '対応機種・電源要件は確認した？',
      required: true,
      options: [
        { id: 'checked', label: '確認済み' },
        { id: 'maybe', label: 'たぶん大丈夫' },
        { id: 'unchecked', label: '未確認' },
        { id: 'unknown', label: 'わからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_tech_after_use',
      type: 'single',
      title: '現場後も使う？',
      required: true,
      options: [
        { id: 'use', label: '使う' },
        { id: 'maybe', label: 'たぶん使う' },
        { id: 'not_use', label: '使わない' },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_itabag_target',
      type: 'single',
      title: '理想の完成イメージは？（フルカバー/推しだけ）',
      required: true,
      options: [
        { id: 'concrete', label: '具体的にある' },
        { id: 'rough', label: 'だいたいある' },
        { id: 'unknown', label: '未定', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_goods_itabag_usage',
      type: 'single',
      title: '痛バの使い方は？',
      required: true,
      options: [
        { id: 'event', label: '現場で使う予定' },
        { id: 'display', label: '展示・鑑賞中心' },
        { id: 'both', label: '現場と展示の両方' },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },

    {
      id: 'q_addon_media_motive',
      type: 'single',
      title: 'このメディアを欲しい主な理由は、キャラ/IP側ですか？ それとも演者・キャスト側ですか？',
      required: true,
      options: [
        { id: 'character_ip', label: 'キャラ・作品・内容面が主な理由', delta: { desire: 66, regretRisk: 45 } },
        { id: 'balanced', label: '両方同じくらい大事', delta: { desire: 62, regretRisk: 56 } },
        { id: 'cast_performer', label: '推し声優・演者・キャスト参加が主な理由', tags: ['actor_fan_primary'], delta: { impulse: 68, regretRisk: 70 } },
        { id: 'unknown', label: 'まだ言語化できていない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_support_scope',
      type: 'single',
      title: '回収したい気持ちは、最推し1人/1キャラ寄り？ それとも箱・グループ寄り？',
      required: true,
      options: [
        { id: 'one_oshi', label: '最推し1人/1キャラ中心', delta: { opportunityCost: 46, regretRisk: 44 } },
        { id: 'balanced', label: 'どちらも少しある', delta: { desire: 58, regretRisk: 54 } },
        { id: 'box_group', label: '箱・グループ全体を支えたい', tags: ['collection_pressure'], delta: { desire: 68, impulse: 60, opportunityCost: 62 } },
        { id: 'unknown', label: 'まだ決めきれていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_collection_budget',
      type: 'single',
      title: '今回は「揃えたい気持ち」と「予算」のどちらを強く守りたい？',
      required: true,
      options: [
        { id: 'efficient', label: '予算優先で、効率よく1枚/1本に絞りたい', delta: { affordability: 68, opportunityCost: 42, impulse: 42 } },
        { id: 'balanced', label: '納得できる範囲なら少し広げてもいい', delta: { affordability: 58, desire: 58, regretRisk: 54 } },
        { id: 'complete', label: '多少負担があっても揃えたい気持ちが強い', tags: ['collection_pressure'], delta: { desire: 68, impulse: 62, opportunityCost: 68 } },
        { id: 'unknown', label: 'まだ整理中', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_edition_intent',
      type: 'single',
      title: '版違いがあるなら、今の気持ちにいちばん近いのは？',
      required: true,
      options: [
        { id: 'standard_only', label: '通常盤/通常版で十分', delta: { affordability: 68, impulse: 42, regretRisk: 44 } },
        { id: 'limited_preferred', label: '初回/限定版が本命だが、1種で満足したい', tags: ['media_limited_preferred'], delta: { desire: 64, impulse: 54, regretRisk: 52 } },
        { id: 'one_best_fit', label: '仕様を見て、自分向けの1種だけ選びたい', tags: ['media_one_best_fit'], delta: { affordability: 62, opportunityCost: 46 } },
        { id: 'all_editions', label: '版違いは基本全部追いたい', tags: ['media_all_editions_ambition', 'collection_pressure'], delta: { desire: 70, impulse: 68, opportunityCost: 74 } },
        { id: 'unknown', label: 'まだ決めていない', tags: ['unknown_info'], delta: { regretRisk: 66, opportunityCost: 62 } },
      ],
    },
    {
      id: 'q_addon_media_single_vs_set_intent',
      type: 'single',
      title: '今回ほしい形は、1点・ベスト1種・選抜回収・フルセットのどれに近い？',
      required: true,
      options: [
        { id: 'one_symbolic_item', label: '象徴になる1点があれば満足しやすい', delta: { affordability: 66, impulse: 40, regretRisk: 42 } },
        { id: 'one_best_fit_version', label: '仕様を見てベストな1種だけ選びたい', delta: { affordability: 64, opportunityCost: 42, regretRisk: 44 } },
        { id: 'selective_subset', label: '必要な版/絵柄/メンバー分だけ選んで回収したい', delta: { affordability: 60, desire: 60, opportunityCost: 50 } },
        { id: 'full_set_bundle', label: 'セット・全版・全員分まで揃えたい', tags: ['collection_pressure'], delta: { desire: 70, impulse: 64, opportunityCost: 74 } },
        { id: 'unknown', label: 'まだ決めきれていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_completion_satisfaction',
      type: 'single',
      title: '全部そろわなくても、ある程度で満足して止まれそう？',
      required: true,
      options: [
        { id: 'high', label: '止まれる。1点/一部でも納得しやすい', delta: { regretRisk: 40, impulse: 40, opportunityCost: 42 } },
        { id: 'medium', label: '工夫すれば止まれそう', delta: { regretRisk: 54, impulse: 52 } },
        { id: 'low', label: '中途半端だとかなり落ち着かない', tags: ['collection_pressure'], delta: { regretRisk: 72, impulse: 68, opportunityCost: 68 } },
        { id: 'unknown', label: 'まだ分からない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_used_market_recovery',
      type: 'single',
      title: '初回窓を逃したり欠けが出たら、あとで埋める前提はありますか？',
      description: '中古/二次流通を主導線にするか、参考にとどめるかを見ます',
      required: true,
      options: [
        { id: 'buy_now_primary', label: '基本は今そろえたい。後追い前提にはしたくない', delta: { urgency: 66, regretRisk: 60 } },
        { id: 'wait_and_patch', label: '急がず、欠けた分だけ後で埋めたい', tags: ['used_market_completion_interest'], delta: { impulse: 42, regretRisk: 46, opportunityCost: 44 } },
        { id: 'reference_only', label: '参考相場として見るのはありだが、主導線にはしにくい', tags: ['used_market_reference_only'], delta: { regretRisk: 54, opportunityCost: 54 } },
        { id: 'avoid_used_market', label: '中古・フリマで埋める前提はできれば避けたい', delta: { rarity: 60, regretRisk: 62, urgency: 60 } },
        { id: 'unknown', label: 'まだ整理できていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_used_market_comfort',
      type: 'single',
      title: 'Mercari / 駿河屋などで後から探すことへの抵抗感は？',
      required: true,
      options: [
        { id: 'high', label: 'かなり平気。遅れや価格差も織り込める', tags: ['used_market_comfort_high'], delta: { impulse: 38, regretRisk: 44, restockChance: 66 } },
        { id: 'medium', label: '条件が合えば使える', tags: ['used_market_comfort_mid'], delta: { regretRisk: 52, restockChance: 58 } },
        { id: 'reference_only', label: '相場の参考にはするが、積極購入は慎重', tags: ['used_market_reference_only'], delta: { regretRisk: 58, restockChance: 54 } },
        { id: 'low', label: '状態・遅れ・不確実さが気になり、できれば避けたい', tags: ['used_market_comfort_low'], delta: { regretRisk: 66, restockChance: 36, rarity: 62 } },
        { id: 'unknown', label: 'まだ分からない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_completion_pressure_type',
      type: 'single',
      title: '「揃えたい圧」の正体はどれに近い？',
      required: true,
      options: [
        { id: 'personal_standard', label: '自分の基準として、揃いを崩したくない', delta: { desire: 58, regretRisk: 56 } },
        { id: 'box_group_desire', label: '箱・グループ全体で揃っていることに意味がある', tags: ['collection_pressure'], delta: { desire: 66, impulse: 60, opportunityCost: 66 } },
        { id: 'bonus_store_pressure', label: '店舗特典・店別差分を落としたくない', tags: ['bonus_pressure_mid', 'store_bonus_collection_pressure'], delta: { impulse: 66, regretRisk: 68, opportunityCost: 70 } },
        { id: 'complete_collection_image', label: '「全部持っている状態」にして安心したい', tags: ['collection_pressure'], delta: { impulse: 72, regretRisk: 70, opportunityCost: 72 } },
        { id: 'mixed', label: 'いくつか混ざっている', delta: { desire: 60, regretRisk: 58, impulse: 58 } },
        { id: 'unknown', label: 'まだ言語化できていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_set_reward_strength',
      type: 'single',
      title: '全版/全員分でそろえた時のごほうびは、どれくらい実体がありますか？',
      description: '収納ケース・連動特典・明確な収録差など、セットで得る意味の強さ',
      required: true,
      options: [
        { id: 'strong', label: '明確にある（連動特典・収納・大きい差分）', delta: { desire: 68, regretRisk: 48 } },
        { id: 'medium', label: '少しあるが、絶対ではない', delta: { desire: 58, regretRisk: 54 } },
        { id: 'weak', label: 'ほぼ自己満足で、セット報酬は弱い', delta: { affordability: 62, opportunityCost: 64, regretRisk: 58 } },
        { id: 'unknown', label: 'まだ比較できていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_member_version',
      type: 'single',
      title: 'メンバー/キャラ別ジャケットやバージョン違いは、どのくらい重要？',
      required: true,
      options: [
        { id: 'none', label: '特に気にしない', delta: { impulse: 44, opportunityCost: 44 } },
        { id: 'specific_version', label: '最推し分だけ合えばよい', delta: { desire: 60, opportunityCost: 52 } },
        { id: 'multiple_versions', label: '複数人/複数版を揃えたい', tags: ['collection_pressure'], delta: { desire: 66, impulse: 62, opportunityCost: 70 } },
        { id: 'unknown', label: 'まだ分からない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_playback_space',
      type: 'single',
      title: '再生環境や保管場所に問題はありませんか？',
      required: true,
      options: [
        { id: 'ready', label: '再生環境・保管ともに問題ない', delta: { regretRisk: 38, opportunityCost: 40 } },
        { id: 'partial', label: 'どちらかは整っている', delta: { regretRisk: 54, opportunityCost: 56 } },
        { id: 'not_ready', label: '未整備で不安がある', tags: ['media_usage_unready'], delta: { regretRisk: 76, opportunityCost: 72 } },
        { id: 'unknown', label: 'まだ確認できていない', tags: ['unknown_info'], delta: { regretRisk: 68, opportunityCost: 62 } },
      ],
    },
    {
      id: 'q_addon_media_limited_pressure',
      type: 'single',
      title: '特典や初回限定がなくても本当に欲しいですか？',
      required: true,
      options: [
        { id: 'yes', label: '特典なしでも欲しい', delta: { impulse: 44, regretRisk: 42 } },
        { id: 'maybe', label: '特典が弱いと迷う', tags: ['bonus_pressure_mid'], delta: { impulse: 58, regretRisk: 60 } },
        { id: 'no', label: '特典・限定が主目的になっている', tags: ['bonus_pressure_high'], delta: { impulse: 72, regretRisk: 75 } },
        { id: 'unknown', label: 'まだ整理できていない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_bonus_importance',
      type: 'single',
      title: '店舗別 bonus は、今回どのくらい本体に近い？',
      required: true,
      options: [
        { id: 'low', label: 'bonus はあれば嬉しいが、商品本体が主役', delta: { impulse: 42, regretRisk: 42 } },
        { id: 'medium', label: '良い bonus がある店を1つ選びたい', tags: ['store_bonus_compare_interest'], delta: { desire: 58, regretRisk: 54 } },
        { id: 'high', label: 'bonus がかなり重要で、弱いと満足しにくい', tags: ['store_bonus_collection_pressure'], delta: { impulse: 68, regretRisk: 70 } },
        { id: 'unknown', label: 'まだ整理できていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_voice_cd_kind',
      type: 'single',
      title: '今回の対象、どのドラマCD文脈に近い？',
      description: '本編ドラマCDなのか、店舗特典ドラマ確認が主なのかを切り分けます',
      required: true,
      options: [
        { id: 'drama_cd_main', label: '本編ドラマCDとして買いたい', tags: ['voice_cd_main'], delta: { desire: 68, regretRisk: 42, opportunityCost: 42 } },
        { id: 'store_bonus_audio', label: '店舗特典ドラマ・特典CD込みで判断したい', tags: ['voice_store_bonus_focus', 'bonus_pressure_mid'], delta: { desire: 64, urgency: 58, regretRisk: 54 } },
        { id: 'adjacent_media', label: 'ドラマ要素は気になるが、主役は別の媒体/仕様', tags: ['voice_adjacent_media'], delta: { desire: 46, impulse: 56, regretRisk: 68, opportunityCost: 70 } },
        { id: 'not_checked', label: 'まだ商品構成を確認できていない', tags: ['unknown_voice_cd_kind'], delta: { regretRisk: 82, opportunityCost: 76, urgency: 54 } },
      ],
    },
    {
      id: 'q_addon_voice_cast_check',
      type: 'single',
      title: 'ドラマCDとして、出演キャスト確認はどれくらい大事？',
      description: '出演者が決め手なら、未確認のまま進めない方が安全です',
      required: true,
      options: [
        { id: 'important_confirmed', label: '大事で、もう確認できている', delta: { desire: 68, regretRisk: 38, opportunityCost: 38 } },
        { id: 'important_unconfirmed', label: '大事だが、まだ確認できていない', tags: ['unknown_voice_cast', 'voice_cast_blocker'], delta: { regretRisk: 82, opportunityCost: 74 } },
        { id: 'not_important', label: '今回はそこまで重要ではない', delta: { regretRisk: 46, opportunityCost: 46 } },
      ],
    },
    {
      id: 'q_addon_voice_bonus_is_audio',
      type: 'single',
      title: '音声特典・店舗特典ドラマの価値はどれくらい？',
      description: '店舗差・先着条件・版違い確認が必要かを見ます',
      required: true,
      options: [
        { id: 'core_audio', label: '特典ドラマ/音声特典そのものが核心', tags: ['bonus_pressure_high', 'voice_bonus_core'], delta: { desire: 74, urgency: 72, impulse: 70, regretRisk: 68 } },
        { id: 'nice_to_have', label: 'あれば嬉しいが、本体優先', tags: ['bonus_pressure_mid'], delta: { desire: 60, urgency: 56, impulse: 54, regretRisk: 54 } },
        { id: 'not_important', label: '特典は重要ではない', delta: { impulse: 40, opportunityCost: 42, regretRisk: 42 } },
        { id: 'not_checked', label: 'まだ調べ切れていない/差が分からない', tags: ['unknown_voice_bonus'], delta: { regretRisk: 78, opportunityCost: 74, urgency: 56 } },
      ],
    },
    {
      id: 'q_addon_voice_listen_timing',
      type: 'single',
      title: 'このドラマCD、実際に聴くタイミングはどれに近い？',
      required: true,
      options: [
        { id: 'listen_soon', label: '近いうちにちゃんと聴く予定', tags: ['voice_listen_ready'], delta: { desire: 74, regretRisk: 40, opportunityCost: 36 } },
        { id: 'maybe_later', label: 'あとで聴くかも/保存寄り', delta: { desire: 56, regretRisk: 54, opportunityCost: 56 } },
        { id: 'archive_main', label: '聴くより所持・回収の意味が強い', tags: ['voice_collecting_main'], delta: { desire: 52, impulse: 68, regretRisk: 68, opportunityCost: 72 } },
        { id: 'not_sure', label: 'まだ自分でも決め切れていない', tags: ['unknown_voice_listen'], delta: { desire: 48, impulse: 58, regretRisk: 72, opportunityCost: 70 } },
      ],
    },
    {
      id: 'q_addon_media_multi_store_tolerance',
      type: 'single',
      title: '複数店舗の bonus を追うなら、どこまで許容できますか？',
      required: true,
      options: [
        { id: 'one_store_ok', label: '1店舗に絞れれば十分', delta: { opportunityCost: 40, regretRisk: 42 } },
        { id: 'compare_then_one', label: '比較はしたいが、最終的には1店舗に絞りたい', tags: ['store_bonus_compare_interest'], delta: { opportunityCost: 52, regretRisk: 50 } },
        { id: 'multi_store_considered', label: '本当に刺さるなら2店舗くらいは検討できる', tags: ['multi_store_bonus_interest'], delta: { desire: 62, opportunityCost: 62 } },
        { id: 'all_bonuses_or_bust', label: '取りこぼしがあるとかなりしんどい', tags: ['multi_store_bonus_pressure'], delta: { impulse: 70, regretRisk: 74, opportunityCost: 74 } },
        { id: 'unknown', label: 'まだ分からない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_split_order_burden',
      type: 'single',
      title: '複数注文・送料増・管理の手間はどのくらい平気？',
      required: true,
      options: [
        { id: 'low', label: 'それ込みでも回せる', delta: { opportunityCost: 42, regretRisk: 46 } },
        { id: 'medium', label: '少しなら許容できる', delta: { opportunityCost: 58, regretRisk: 56 } },
        { id: 'high', label: 'かなり負担で、後悔しやすい', tags: ['split_order_burden_high'], delta: { opportunityCost: 78, regretRisk: 76, impulse: 60 } },
        { id: 'unknown', label: 'まだ想像できていない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_media_random_goods_intent',
      type: 'single',
      title: 'このメディア判断と一緒に、ランダム/ブラインド特典や付随グッズの止めどきも整理したい？',
      required: true,
      options: [
        { id: 'none', label: '今回はメディア版違いだけ整理したい', delta: { impulse: 44, opportunityCost: 46 } },
        { id: 'present', label: 'ランダム特典/付随グッズの止めどきも一緒に見たい', tags: ['mixed_media_random_goods'], delta: { impulse: 58, regretRisk: 58 } },
        { id: 'unknown', label: 'まだ分からない', tags: ['unknown_info'], delta: { regretRisk: 64, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_cap',
      type: 'single',
      title: 'ブラインドは「何個で止める」上限を決めてる？',
      required: true,
      options: [
        { id: 'used_to_it', label: '決めている（上限で止められる）', delta: { impulse: 38, regretRisk: 40 } },
        { id: 'neutral', label: 'だいたい決めている', delta: { impulse: 52, regretRisk: 52 } },
        { id: 'not_good', label: '決めても超えがち', delta: { impulse: 78, regretRisk: 72 } },
        { id: 'unknown', label: 'まだ決めていない', tags: ['unknown_info'], delta: { impulse: 68, regretRisk: 66, opportunityCost: 62 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_exit',
      type: 'single',
      title: 'どこまで開封したら止まれそうですか？',
      required: true,
      options: [
        { id: 'complete', label: 'フルセット/コンプ寄りで揃えたい', tags: ['blind_draw_target_full_set'], delta: { desire: 66, opportunityCost: 62, regretRisk: 60 } },
        { id: 'oshi_only', label: '本命1〜2種だけ狙いたい', tags: ['blind_draw_target_one_or_few'], delta: { desire: 62, regretRisk: 46 } },
        { id: 'mixed', label: '引きながら様子見で調整したい', tags: ['blind_draw_target_mixed'], delta: { impulse: 62, regretRisk: 58 } },
        { id: 'fun', label: '運試し/開封そのものを楽しみたい', tags: ['blind_draw_target_fun'], delta: { desire: 60, impulse: 52, regretRisk: 44 } },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_duplicate_tolerance',
      type: 'single',
      title: '被りが出た時の許容度は？',
      required: true,
      options: [
        { id: 'high', label: '被っても楽しめる/保管できる', tags: ['blind_draw_duplicate_high'], delta: { regretRisk: 40, opportunityCost: 42 } },
        { id: 'medium', label: '少しなら大丈夫', tags: ['blind_draw_duplicate_medium'], delta: { regretRisk: 56, opportunityCost: 56 } },
        { id: 'low', label: '被りはかなりつらい', tags: ['blind_draw_duplicate_low'], delta: { regretRisk: 80, opportunityCost: 74, impulse: 62 } },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 66, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_trade_intent',
      type: 'single',
      title: '最推しが出なかった場合、交換や中古で補う前提ですか？',
      required: true,
      options: [
        { id: 'yes', label: '交換先があり回せる', delta: { regretRisk: 42, opportunityCost: 45 } },
        { id: 'maybe', label: '条件が合えば回せる', delta: { regretRisk: 55, opportunityCost: 54 } },
        { id: 'no', label: '交換せず抱える', delta: { regretRisk: 72, opportunityCost: 70 } },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_exchange_friction',
      type: 'single',
      title: '交換するなら、連絡・梱包・待ち時間の負担はどのくらい平気？',
      required: true,
      options: [
        { id: 'low', label: 'それ込みでも回せる', tags: ['blind_draw_exchange_friction_low'], delta: { regretRisk: 42, opportunityCost: 46 } },
        { id: 'medium', label: '少しなら対応できる', tags: ['blind_draw_exchange_friction_medium'], delta: { regretRisk: 56, opportunityCost: 58 } },
        { id: 'high', label: 'かなり負担に感じる', tags: ['blind_draw_exchange_friction_high'], delta: { regretRisk: 76, opportunityCost: 74 } },
        { id: 'unknown', label: 'まだ想像できない', tags: ['unknown_info'], delta: { regretRisk: 66, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_single_fallback',
      type: 'single',
      title: '止めた後は中古/単品回収に切り替えられますか？',
      required: true,
      options: [
        { id: 'now', label: '必要ならすぐ切り替えられる', tags: ['blind_draw_single_fallback_now'], delta: { regretRisk: 42, opportunityCost: 44 } },
        { id: 'after_stop', label: '上限まで引いたら切り替える', tags: ['blind_draw_single_fallback_after_stop'], delta: { regretRisk: 52, opportunityCost: 50 } },
        { id: 'avoid', label: 'できれば単品回収は避けたい', tags: ['blind_draw_single_fallback_avoid'], delta: { regretRisk: 68, opportunityCost: 66 } },
        { id: 'unknown', label: 'まだ決めていない', tags: ['unknown_info'], delta: { regretRisk: 66, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_stop_budget',
      type: 'single',
      title: '今回の「ここで止める」予算ラインは？',
      required: true,
      options: [
        { id: 'strict', label: '厳守ラインがある', tags: ['blind_draw_stop_budget_strict'], delta: { impulse: 40, regretRisk: 42 } },
        { id: 'soft', label: 'だいたいの目安はある', tags: ['blind_draw_stop_budget_soft'], delta: { impulse: 54, regretRisk: 54 } },
        { id: 'over_limit', label: 'もう超えそう/超えている', tags: ['blind_draw_stop_budget_over_limit'], delta: { affordability: 26, regretRisk: 82, opportunityCost: 76, impulse: 70 } },
        { id: 'unknown', label: 'まだ決めていない', tags: ['unknown_info'], delta: { regretRisk: 68, opportunityCost: 62, impulse: 66 } },
      ],
    },
    {
      id: 'q_addon_blind_draw_miss_pain',
      type: 'single',
      title: '本命が出なかった時のしんどさは？',
      required: true,
      options: [
        { id: 'low', label: '運試しとして割り切れる', delta: { regretRisk: 42, impulse: 44 } },
        { id: 'mid', label: '少し引きずる', delta: { regretRisk: 58, impulse: 56 } },
        { id: 'high', label: 'かなり後悔しそう', delta: { regretRisk: 80, impulse: 68, opportunityCost: 70 } },
        { id: 'unknown', label: 'わからない', tags: ['unknown_info'], delta: { regretRisk: 66, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_ticket_schedule',
      type: 'single',
      title: 'この日程に確実に行ける？（他予定との衝突）',
      required: true,
      options: [
        { id: 'ready', label: 'ほぼ確実に行ける', delta: { regretRisk: 38, opportunityCost: 42 } },
        { id: 'some_risk', label: 'やや不確定（調整が必要）', delta: { regretRisk: 56, opportunityCost: 54 } },
        { id: 'risk', label: '衝突リスクが高い', delta: { regretRisk: 78, opportunityCost: 74 } },
      ],
    },
    {
      id: 'q_addon_ticket_resale_rule',
      type: 'single',
      title: 'キャンセル・譲渡・払い戻し条件は確認した？',
      required: true,
      options: [
        { id: 'checked', label: '確認済み', delta: { regretRisk: 40, opportunityCost: 45 } },
        { id: 'partly', label: '一部だけ確認', delta: { regretRisk: 58, opportunityCost: 56 } },
        { id: 'not_yet', label: '未確認', delta: { regretRisk: 76, opportunityCost: 72 } },
      ],
    },
    {
      id: 'q_addon_ticket_trip_load',
      type: 'single',
      title: '交通・宿・総費用まで含めた負担感は？',
      required: true,
      options: [
        { id: 'light', label: '追加負担は軽い', delta: { affordability: 70, opportunityCost: 44 } },
        { id: 'medium', label: 'やや重い', delta: { affordability: 56, opportunityCost: 58 } },
        { id: 'heavy', label: 'かなり重い', delta: { affordability: 36, opportunityCost: 76, regretRisk: 70 } },
      ],
    },
    {
      id: 'q_addon_ticket_next_chance',
      type: 'single',
      title: 'この日程を逃した場合の次の機会は？',
      required: true,
      options: [
        { id: 'rare', label: 'この日程ほぼ一択', delta: { urgency: 76, rarity: 72, restockChance: 30 } },
        { id: 'maybe', label: '別日/配信の可能性はある', delta: { urgency: 56, rarity: 54, restockChance: 48 } },
        { id: 'likely', label: '次の機会が高そう', delta: { urgency: 35, rarity: 40, restockChance: 70 } },
        { id: 'unknown', label: '未確認', tags: ['unknown_info'], delta: { regretRisk: 63, opportunityCost: 58 } },
      ],
    },
    {
      id: 'q_addon_preorder_timeline',
      type: 'single',
      title: '待ち期間（発売・発送まで）を許容できる？',
      required: true,
      options: [
        { id: 'yes', label: '待てる（納得している）', delta: { regretRisk: 42, opportunityCost: 48 } },
        { id: 'no', label: '長い待ちはつらい', delta: { regretRisk: 74, opportunityCost: 72 } },
        { id: 'unknown', label: 'まだ見通せない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_preorder_decay',
      type: 'single',
      title: '届く頃まで熱量を保てそう？',
      required: true,
      options: [
        { id: 'stable', label: '届く頃も楽しみにできる', delta: { desire: 68, regretRisk: 40 } },
        { id: 'uncertain', label: '少し不安', delta: { desire: 54, regretRisk: 58 } },
        { id: 'drop', label: '熱が下がりそう', delta: { desire: 38, regretRisk: 74, opportunityCost: 70 } },
      ],
    },
    {
      id: 'q_addon_preorder_compare_loss',
      type: 'single',
      title: '今予約すると、後から比較する余地は減る？',
      required: true,
      options: [
        { id: 'small', label: '比較機会はあまり失わない', delta: { opportunityCost: 44, regretRisk: 44 } },
        { id: 'mid', label: '一部失う', delta: { opportunityCost: 58, regretRisk: 56 } },
        { id: 'large', label: 'ほぼ比較できなくなる', delta: { opportunityCost: 76, regretRisk: 72 } },
      ],
    },
    {
      id: 'q_addon_preorder_restock',
      type: 'single',
      title: '（旧）受注再開・再販の可能性を確認した？',
      required: true,
      options: [
        { id: 'checked', label: '確認した' },
        { id: 'heard', label: '噂レベルで知っている' },
        { id: 'unknown', label: 'わからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_used_condition',
      type: 'single',
      title: '中古の状態（キズ/欠品）をどこまで許容できる？',
      required: true,
      options: [
        { id: 'ok', label: '軽微なら許容できる', delta: { regretRisk: 45 } },
        { id: 'careful', label: '条件が揃えば許容', delta: { regretRisk: 56, opportunityCost: 55 } },
        { id: 'hard', label: '状態不安が大きい', delta: { regretRisk: 78, opportunityCost: 72 } },
      ],
    },
    {
      id: 'q_addon_used_price_gap',
      type: 'single',
      title: '新品との差額は納得できる？',
      required: true,
      options: [
        { id: 'worth', label: '納得できる' },
        { id: 'small', label: '差額が小さい' },
        { id: 'unknown', label: '比較できていない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_used_defect_return',
      type: 'single',
      title: 'キズ/欠品の許容と返品条件は確認した？',
      required: true,
      options: [
        { id: 'checked_ok', label: '確認済みで許容できる' },
        { id: 'partial', label: '一部だけ確認した' },
        { id: 'not_ok', label: '不安がある/未確認' },
        { id: 'unknown', label: 'わからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_used_authenticity',
      type: 'single',
      title: '真贋証明（正規品の根拠）は重要？',
      required: true,
      options: [
        { id: 'must', label: '必須（証明がないと買わない）' },
        { id: 'prefer', label: 'できれば欲しい' },
        { id: 'not_needed', label: 'あまり重視しない' },
        { id: 'unknown', label: 'まだわからない', tags: ['unknown_info'], delta: { regretRisk: 65, opportunityCost: 60 } },
      ],
    },
    {
      id: 'q_addon_used_seller_trust',
      type: 'single',
      title: '出品者/店舗の信頼度と返品対応は？',
      required: true,
      options: [
        { id: 'high', label: '評価・返品条件ともに安心', delta: { regretRisk: 42, opportunityCost: 46 } },
        { id: 'medium', label: '評価は普通、条件は一部確認', delta: { regretRisk: 58, opportunityCost: 56 } },
        { id: 'low', label: '信頼根拠が弱い/返品厳しい', delta: { regretRisk: 80, opportunityCost: 72 } },
        { id: 'unknown', label: '未確認', tags: ['unknown_info'], delta: { regretRisk: 68, opportunityCost: 62 } },
      ],
    },
  ],
};
