import type { ScenarioCard } from "./types";
/**
 * 推し活トーンの「例から選ぶ」シナリオカード
 * - 友達みたいに寄り添う
 * - FOMOを否定しない
 * - 線引き（上限/条件）に落とす
 */
export const SCENARIO_CARDS_JA_OSHIKATSU: ScenarioCard[] = [
  {
    id: "gds_store_close_10m",
    title: "中古屋があと10分で閉店…！",
    example: "目の前に欲しかったグッズ。心が騒ぐやつ。",
    kind: "goods",
    mode: "short",
    chips: [
      "時間がない",
      "勢いが入りやすい",
      "まず仮判定",
    ],
    oneLine: "買うなら上限を先に決めて即決。迷うなら写真だけ撮って保留でもOK。",
    tags: [
      "店頭",
      "中古",
      "閉店",
      "衝動",
    ],
  },
  {
    id: "gds_event_blind",
    title: "会場でブラインド（ランダム）を見つけた",
    example: "推しが出るか分からない。沼の香り。",
    kind: "goods",
    mode: "short",
    chips: [
      "ランダムは上振れ狙い",
      "後悔しやすい",
      "上限が命",
    ],
    oneLine: "『◯個まで』を決められないなら、今日はやめるのが優しい。",
    tags: [
      "会場",
      "ランダム",
      "沼",
    ],
  },
  {
    id: "gds_ichiban_kuji",
    title: "一番くじ、目の前で残り少ない",
    example: "残り枚数が減って焦る。心拍数あがる。",
    kind: "goods",
    mode: "short",
    chips: [
      "希少性で判断がブレる",
      "焦りが入る",
      "まず線引き",
    ],
    oneLine: "狙いが明確なら回数上限を決めてGO。曖昧なら保留/撤退でOK。",
    tags: [
      "くじ",
      "希少",
      "焦り",
    ],
  },
  {
    id: "gds_popup_last_stock",
    title: "ポップアップで『ラストです』と言われた",
    example: "その一言、強い。",
    kind: "goods",
    mode: "short",
    chips: [
      "FOMOが強い",
      "今買う理由が必要",
      "仮判定で落ち着く",
    ],
    oneLine: "『今買う理由』が言えないなら保留。再販/中古の逃げ道チェック。",
    tags: [
      "ポップアップ",
      "限定",
      "FOMO",
    ],
  },
  {
    id: "gds_online_drop_soon",
    title: "オンライン販売、開始10分前でソワソワ",
    example: "カート戦争の予感。焦りスイッチ入る。",
    kind: "goods",
    mode: "short",
    chips: [
      "時間がない",
      "テンション上がる",
      "最短で安全運転",
    ],
    oneLine: "買うなら『上限』『置き場所』『後悔したら売る条件』だけ30秒で決めよ。",
    tags: [
      "オンライン",
      "争奪",
      "開始前",
    ],
  },
  {
    id: "gds_animeite_reserved_today",
    title: "アニメイトの予約、今日まで！",
    example: "受注/予約の締切に追われるやつ。",
    kind: "goods",
    mode: "medium",
    chips: [
      "期限あり",
      "でも少し時間はある",
      "保留条件が作れる",
    ],
    oneLine: "まずは『今月の上限』を確認。超えるなら保留→再販/中古で回収でもOK。",
    tags: [
      "アニメイト",
      "予約",
      "締切",
    ],
  },
  {
    id: "gds_preorder_tonight",
    title: "受注締切が今日23:59",
    example: "価格は6,000円。受注生産で迷う。",
    kind: "goods",
    mode: "medium",
    chips: [
      "少し時間がある",
      "納得して決める",
      "保留条件OK",
    ],
    oneLine: "『買わないと困る？』がNoなら、24h保留→まだ欲しければ買う。",
    tags: [
      "受注",
      "締切",
      "中価格",
    ],
  },
  {
    id: "gds_store_bonus_choice",
    title: "店舗別特典、どこで買うか迷う",
    example: "特典絵柄が全部良い。選べない。",
    kind: "goods",
    mode: "long",
    chips: [
      "候補が多い",
      "比較が必要",
      "後悔しやすい",
    ],
    oneLine: "『一番見返す特典』を1つ決めて、他は潔く切ると楽。",
    tags: [
      "店舗特典",
      "比較",
      "選択肢",
    ],
  },
  {
    id: "gds_bundle_vs_single",
    title: "セット（特典付き）か単品かで迷う",
    example: "特典が魅力、でもセット高い…！",
    kind: "goods",
    mode: "long",
    chips: [
      "総額が大きくなる",
      "価値の分解が必要",
      "機会コスト",
    ],
    oneLine: "特典が“後で単体で欲しくなる”ならセット。曖昧なら単品＋保留でOK。",
    tags: [
      "セット",
      "特典",
      "比較",
    ],
  },
  {
    id: "gds_fig_preorder_next_year",
    title: "来年発送の高額フィギュア、予約する？",
    example: "¥25,000。締切は1週間後。時間はある。",
    kind: "goods",
    mode: "long",
    chips: [
      "高額",
      "未来の自分に影響",
      "整理して納得",
    ],
    oneLine: "置き場所・支払い時期・再販/中古相場を見てから決めると後悔が減る。",
    tags: [
      "フィギュア",
      "予約",
      "高額",
    ],
  },
  {
    id: "gds_preorder_overlap",
    title: "予約が重なって、来月の請求が怖い",
    example: "複数の予約品が同じ月に来そう。",
    kind: "goods",
    mode: "long",
    chips: [
      "総額が見えない",
      "予算圧が強い",
      "整理が必要",
    ],
    oneLine: "『来月の推し活上限』を決めて、超える分は保留/キャンセル候補に。",
    tags: [
      "予約",
      "重なり",
      "予算",
    ],
  },
  {
    id: "gds_after_payday",
    title: "給料日直後でテンション上がってる",
    example: "財布が強く見える日。",
    kind: "goods",
    mode: "medium",
    chips: [
      "衝動が強い",
      "判断が甘くなる",
      "冷却が効く",
    ],
    oneLine: "24時間保留。明日も“まだ欲しい”なら買う、でOK。",
    tags: [
      "給料日",
      "衝動",
      "冷却",
    ],
  },
  {
    id: "gds_space_problem",
    title: "置き場所が限界。でも欲しい。",
    example: "飾る/収納がもうパンパン。",
    kind: "goods",
    mode: "long",
    chips: [
      "生活への影響",
      "後悔ポイントになりやすい",
      "トレードオフ",
    ],
    oneLine: "買うなら『何を手放すか』を先に決める。決められないなら保留が優しい。",
    tags: [
      "収納",
      "生活",
      "トレードオフ",
    ],
  },
  {
    id: "gds_itabag_more",
    title: "痛バッグ用に缶バッジを追加する？",
    example: "あと数個で完成。でも出費が積み上がる。",
    kind: "goods",
    mode: "medium",
    chips: [
      "積み上げ出費",
      "上限設定が効く",
      "満足は上がる",
    ],
    oneLine: "完成ライン（必要個数）を決めて、それ以上はストップ。未来の財布を守ろ。",
    tags: [
      "痛バ",
      "缶バ",
      "積み上げ",
    ],
  },
  {
    id: "gds_new_release_fomo",
    title: "新情報の供給で心が沸騰してる",
    example: "発表直後の熱で全部ほしくなるやつ。",
    kind: "goods",
    mode: "medium",
    chips: [
      "熱が高い",
      "判断が粗くなる",
      "冷却が効く",
    ],
    oneLine: "公式画像を保存して24h保留。熱が落ちた後の自分に決めてもらお。",
    tags: [
      "供給",
      "新作",
      "冷却",
    ],
  },
  {
    id: "gds_lottery_purchase_right",
    title: "購入権が当たった（期限48h）",
    example: "“当たったから買う”になりそうで怖い。",
    kind: "goods",
    mode: "medium",
    chips: [
      "期限あり",
      "希少性が強い",
      "納得が必要",
    ],
    oneLine: "『欲しい理由』が弱いなら保留。権利＝義務じゃない、でOK。",
    tags: [
      "購入権",
      "抽選",
      "期限",
    ],
  },
  {
    id: "gds_random_cheki",
    title: "ランダムチェキを追加で買いそう",
    example: "推し引きたい気持ちが強い。",
    kind: "goods",
    mode: "medium",
    chips: [
      "ランダムは沼",
      "上限が大事",
      "後悔しやすい",
    ],
    oneLine: "上限（枚数/金額）を先に決めてから。決められないなら今日はストップ。",
    tags: [
      "チェキ",
      "ランダム",
      "沼",
    ],
  },
  {
    id: "gds_blu_ray_bonus",
    title: "円盤の連動購入特典、追うか迷う",
    example: "特典が魅力。でも複数枚は痛い。",
    kind: "goods",
    mode: "long",
    chips: [
      "総額が大きい",
      "特典価値の見積もり",
      "機会コスト",
    ],
    oneLine: "特典を中古で回収できる可能性も含めて『最安で満足する道』を探そ。",
    tags: [
      "円盤",
      "連動特典",
      "総額",
    ],
  },
  {
    id: "gds_subscription_box",
    title: "推しグッズの定期便（サブスク）を契約する？",
    example: "毎月届くのは嬉しいけど続く支払いが不安。",
    kind: "goods",
    mode: "long",
    chips: [
      "継続コスト",
      "やめ時が難しい",
      "長期判断",
    ],
    oneLine: "まずは3ヶ月分の総額で考える。続かなそうなら単発で十分。",
    tags: [
      "サブスク",
      "継続",
      "予算",
    ],
  },
  {
    id: "tkt_general_sale_5m",
    title: "一般販売まであと5分…買う？",
    example: "迷ってるのに時間がない。",
    kind: "ticket",
    mode: "short",
    chips: [
      "時間がない",
      "判断速度が優先",
      "まず仮判定",
    ],
    oneLine: "買うなら上限を決めて即決。迷うなら今回は見送り→次の機会に備えよ。",
    tags: [
      "一般",
      "開始直前",
      "即決",
    ],
  },
  {
    id: "tkt_same_day",
    title: "当日券が出た。行く？",
    example: "予定は空いてる。心が揺れる。",
    kind: "ticket",
    mode: "short",
    chips: [
      "今決める必要",
      "感情で揺れやすい",
      "最短で確認",
    ],
    oneLine: "“行った後の自分”が笑ってそうならGO。疲れが勝つなら保留/やめるも正解。",
    tags: [
      "当日券",
      "即時",
      "感情",
    ],
  },
  {
    id: "tkt_lottery_deadline_today",
    title: "抽選締切が今日。席種で迷う（2択）",
    example: "S席とA席。価格差あり。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "期限あり",
      "でも整理はできる",
      "後悔ポイント確認",
    ],
    oneLine: "推し度が高いなら体験優先。迷うなら安い方で『参加』を確保でもOK。",
    tags: [
      "抽選",
      "席種",
      "締切",
    ],
  },
  {
    id: "tkt_fc_advance",
    title: "FC先行、応募するか迷う",
    example: "当たるか分からないのに悩む。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "期待で揺れる",
      "条件整理が効く",
      "保留もあり",
    ],
    oneLine: "応募＝確定じゃない。上限と日程だけ確認して“応募だけ”するのも手。",
    tags: [
      "FC",
      "先行",
      "応募",
    ],
  },
  {
    id: "tkt_resale_available",
    title: "公式リセールがある（焦りにくい）",
    example: "買い逃してもチャンスがありそう。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "緊急度が下がる",
      "冷静に判断",
      "保留が強い",
    ],
    oneLine: "いったん保留→リセール開始日に再診断、が一番メンタルに優しい。",
    tags: [
      "リセール",
      "保留",
      "再検討",
    ],
  },
  {
    id: "tkt_price_surge_resale",
    title: "二次流通の相場が急騰して焦る",
    example: "値段に煽られてる気がする。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "相場は心を揺らす",
      "後悔しやすい",
      "上限が命",
    ],
    oneLine: "上限超えなら撤退。別日/配信/次回に切り替えるのが強い。",
    tags: [
      "二次流通",
      "相場",
      "上限",
    ],
  },
  {
    id: "tkt_travel_total_30k",
    title: "遠征＋宿泊で総額3万円超えそう",
    example: "交通＋宿＋チケット。でかい。",
    kind: "ticket",
    mode: "long",
    chips: [
      "総額が大きい",
      "時間も体力も動く",
      "生活への影響",
    ],
    oneLine: "翌月の固定費・休み・体力まで含めて“行ける”か判断しよ。",
    tags: [
      "遠征",
      "宿泊",
      "高額",
    ],
  },
  {
    id: "tkt_multiple_seats",
    title: "席種が多い（3つ以上）＆価格差も大きい",
    example: "VIP/指定/見切れ/注釈…悩む。",
    kind: "ticket",
    mode: "long",
    chips: [
      "比較が複雑",
      "後悔しやすい",
      "優先順位が必要",
    ],
    oneLine: "優先は『体験』か『費用』か、まず決める。決まれば席は自然に決まる。",
    tags: [
      "席種",
      "比較",
      "体験",
    ],
  },
  {
    id: "tkt_visibility_tradeoff",
    title: "見切れ/注釈席で安く行くか迷う",
    example: "体験が読めないのが怖い。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "体験の最低ライン",
      "価格とのトレードオフ",
      "中で十分",
    ],
    oneLine: "『見えないと辛い』など最低条件を決めてから。条件満たさないならやめる。",
    tags: [
      "見切れ",
      "注釈",
      "条件",
    ],
  },
  {
    id: "tkt_group_coordination",
    title: "同行者が複数で、遠征計画もセット",
    example: "ホテル/移動/予算…要素が多い。",
    kind: "ticket",
    mode: "long",
    chips: [
      "条件が多い",
      "調整コスト",
      "全体で判断",
    ],
    oneLine: "全員の上限と必須条件を先に揃える。合わないなら見送るのも優しさ。",
    tags: [
      "同行",
      "調整",
      "計画",
    ],
  },
  {
    id: "tkt_streaming_vs_onsite",
    title: "現地遠征か配信か迷う",
    example: "価格差が大きい。悩む。",
    kind: "ticket",
    mode: "long",
    chips: [
      "選択肢の比較",
      "費用差が大きい",
      "後悔ポイント整理",
    ],
    oneLine: "『現地でしか得られない価値』が明確なら遠征。曖昧なら配信が強い。",
    tags: [
      "配信",
      "遠征",
      "比較",
    ],
  },
  {
    id: "tkt_timeoff_risk",
    title: "休み取れるか怪しいのに申し込みたい",
    example: "当たった後が怖い（キャンセル難）。",
    kind: "ticket",
    mode: "long",
    chips: [
      "欠席リスク",
      "損失の確認",
      "長で整理",
    ],
    oneLine: "譲渡/リセール可否を確認してから応募。逃げ道がないなら保留が安全。",
    tags: [
      "欠席",
      "リスク",
      "抽選",
    ],
  },
  {
    id: "tkt_multi_days_festival",
    title: "フェス、複数日券か単日券か迷う",
    example: "推し以外も出るけど…？",
    kind: "ticket",
    mode: "long",
    chips: [
      "比較が複雑",
      "総額が膨らむ",
      "満足期待を整理",
    ],
    oneLine: "『推し以外も楽しめる？』がYesなら複数日。Noなら単日が正解率高い。",
    tags: [
      "フェス",
      "複数日",
      "総額",
    ],
  },
  {
    id: "tkt_parental_permission",
    title: "親の許可/お金の相談が必要",
    example: "決めてもすぐ動けない。",
    kind: "ticket",
    mode: "long",
    chips: [
      "外部要因あり",
      "条件整理が先",
      "相談しやすくする",
    ],
    oneLine: "必要条件（お金/同伴/時間）をリスト化してから相談すると通りやすい。",
    tags: [
      "家族",
      "相談",
      "条件",
    ],
  },
  {
    id: "gds_comiket_preorder",
    title: "コミケ新刊セット、通販で迷う",
    example: "送料も入れると地味に高い。",
    kind: "goods",
    mode: "medium",
    chips: [
      "限定で焦りやすい",
      "送料で総額UP",
      "保留条件が作れる",
    ],
    oneLine: "総額（送料込み）で考える。『送料込みでも納得？』で判断しよ。",
    tags: [
      "コミケ",
      "通販",
      "送料",
    ],
  },
  {
    id: "gds_collab_cafe",
    title: "コラボカフェ、グッズ付きメニューを迷う",
    example: "コースター欲しい。でも積み上がる。",
    kind: "goods",
    mode: "medium",
    chips: [
      "積み上げ注意",
      "限定要素あり",
      "線引きが効く",
    ],
    oneLine: "本命を1つ決めて、他はやめる/保留。『全部』は財布が泣く。",
    tags: [
      "コラボ",
      "カフェ",
      "積み上げ",
    ],
  },
  {
    id: "gds_mercari_found",
    title: "メルカリで“相場より安い”のを見つけた",
    example: "今逃すと…って思うやつ。",
    kind: "goods",
    mode: "medium",
    chips: [
      "お得感で焦る",
      "状態確認が必要",
      "保留でもOK",
    ],
    oneLine: "即決前に状態/出品者/相場を1分チェック。問題なければGO。",
    tags: [
      "メルカリ",
      "中古",
      "相場",
    ],
  },
  {
    id: "gds_rerun_risk_unknown",
    title: "再販あるか分からない限定グッズ",
    example: "情報が少なくて不安。",
    kind: "goods",
    mode: "medium",
    chips: [
      "不確実性が高い",
      "FOMOが強い",
      "確認が効く",
    ],
    oneLine: "公式の過去傾向を5分だけ見る→それでも不安なら保留でOK。",
    tags: [
      "再販",
      "限定",
      "不確実",
    ],
  },
  {
    id: "gds_multiple_variants_three",
    title: "同キャラのアクスタが3種、全部かわいい",
    example: "絵柄違いで全部欲しくなる。",
    kind: "goods",
    mode: "long",
    chips: [
      "候補が多い",
      "比較が必要",
      "後悔しやすい",
    ],
    oneLine: "『一番飾りたい絵柄』を1つ決める。残りは写真保存で満足させよ。",
    tags: [
      "アクスタ",
      "比較",
      "選択肢",
    ],
  },
  {
    id: "tkt_two_days_choice",
    title: "2日程ある。どっち行く？",
    example: "仕事/学校と被りそうで悩む。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "スケジュールが鍵",
      "欠席リスク",
      "中で十分",
    ],
    oneLine: "最悪の欠席リスクが低い日を選ぶ。迷うなら“翌日が楽”な方。",
    tags: [
      "日程",
      "スケジュール",
      "欠席",
    ],
  },
];
