import type { ScenarioCard } from "./types";
/**
 * "例から選ぶ" scenario cards for Japanese ACG / 推し活 use cases.
 * Keep copy casual, non-judgmental.
 */
export const SCENARIO_CARDS_JA: ScenarioCard[] = [
  {
    id: "gds_store_close_10m",
    title: "中古屋があと10分で閉店",
    example: "目の前の棚に欲しかったグッズがある。",
    kind: "goods",
    mode: "short",
    chips: [
      "締切が超近い",
      "今は速度が優先",
      "まず仮判定",
    ],
    oneLine: "買うなら上限を決めて即決。迷うなら写真だけ撮って保留。",
    tags: [
      "店頭",
      "中古",
      "閉店",
      "衝動",
    ],
  },
  {
    id: "gds_event_blind",
    title: "会場でブラインド（ランダム）を見つけた",
    example: "推しが出るか分からないランダム商品。",
    kind: "goods",
    mode: "short",
    chips: [
      "勢い買いになりやすい",
      "後悔リスク高め",
      "最短でブレーキ",
    ],
    oneLine: "上限（◯個まで）を先に決める。決められないならやめる寄り。",
    tags: [
      "会場",
      "ランダム",
      "FOMO",
    ],
  },
  {
    id: "gds_popup_last_stock",
    title: "ポップアップで残りわずかと言われた",
    example: "店員さんに『ラストです』と言われる。",
    kind: "goods",
    mode: "short",
    chips: [
      "希少性で判断がブレる",
      "FOMOが強い",
      "仮判定で落ち着く",
    ],
    oneLine: "“今買う理由”を1つ言えないなら保留。再販/相場を確認。",
    tags: [
      "ポップアップ",
      "限定",
      "希少性",
    ],
  },
  {
    id: "gds_online_drop_soon",
    title: "オンライン販売が開始10分前",
    example: "カート戦争になりそうで焦る。",
    kind: "goods",
    mode: "short",
    chips: [
      "時間がない",
      "テンション高まりがち",
      "まず安全運転",
    ],
    oneLine: "買うなら「上限」「置き場所」「後悔したら売る条件」を30秒で決める。",
    tags: [
      "オンライン",
      "開始前",
      "争奪",
    ],
  },
  {
    id: "gds_preorder_tonight",
    title: "今日23:59までの受注",
    example: "価格は6,000円、受注生産。",
    kind: "goods",
    mode: "medium",
    chips: [
      "少し時間がある",
      "予算と後悔ポイント",
      "納得して決める",
    ],
    oneLine: "“買わないと困る？”“代替ある？”を確認してから決める。",
    tags: [
      "受注",
      "締切",
      "中価格",
    ],
  },
  {
    id: "gds_limited_but_rerun",
    title: "限定セットだけど再販の可能性もありそう",
    example: "過去に再販があったシリーズ。",
    kind: "goods",
    mode: "medium",
    chips: [
      "FOMOが強い",
      "再販/中古が鍵",
      "保留条件が作れる",
    ],
    oneLine: "再販情報・中古相場を5分だけ調べる→その結果で判断。",
    tags: [
      "限定",
      "再販",
      "相場",
    ],
  },
  {
    id: "gds_always_available_budget_tight",
    title: "定番商品だけど今月の出費が多い",
    example: "いつでも買えそう、でも財布が厳しい。",
    kind: "goods",
    mode: "medium",
    chips: [
      "緊急じゃない",
      "予算圧力が強い",
      "保留が有効",
    ],
    oneLine: "“来月の自分が買ってOKか”で判断。保留なら上限日を決める。",
    tags: [
      "定番",
      "予算",
      "冷却",
    ],
  },
  {
    id: "gds_gacha_after_payday",
    title: "給料日直後でテンションが上がってる",
    example: "つい課金しがちなタイミング。",
    kind: "goods",
    mode: "medium",
    chips: [
      "衝動が強い",
      "後悔しやすい",
      "冷却が効く",
    ],
    oneLine: "24時間だけ保留して、まだ欲しいなら買う。",
    tags: [
      "課金",
      "衝動",
      "冷却",
    ],
  },
  {
    id: "gds_collab_cafe_menu",
    title: "コラボカフェでグッズ付きメニューを迷う",
    example: "限定コースターが欲しい。",
    kind: "goods",
    mode: "medium",
    chips: [
      "限定要素あり",
      "満足は大きい",
      "でも単価が積み上がる",
    ],
    oneLine: "“本命は何か”を1つ決めて、他はやめる/保留。",
    tags: [
      "コラボ",
      "限定",
      "積み上げ",
    ],
  },
  {
    id: "gds_fig_preorder_next_year",
    title: "来年発送の高額フィギュアを予約するか迷う",
    example: "25,000円、予約締切は1週間後。",
    kind: "goods",
    mode: "long",
    chips: [
      "高額",
      "時間がある",
      "後悔コスト大",
    ],
    oneLine: "置き場所・支払いタイミング・再販/中古を整理してから決める。",
    tags: [
      "フィギュア",
      "予約",
      "高額",
    ],
  },
  {
    id: "gds_multiple_variants_three",
    title: "同キャラのアクスタが3種類、どれにするか迷う",
    example: "絵柄違いで全部欲しくなる。",
    kind: "goods",
    mode: "long",
    chips: [
      "候補が多い",
      "比較が必要",
      "後悔しやすい",
    ],
    oneLine: "優先順位（絵柄/サイズ/飾りやすさ）を決めて1つに絞る。",
    tags: [
      "アクスタ",
      "比較",
      "選択肢",
    ],
  },
  {
    id: "gds_bundle_vs_single",
    title: "セット買い（特典付き）か単品か迷う",
    example: "セットは高いが特典が魅力。",
    kind: "goods",
    mode: "long",
    chips: [
      "選択肢の比較",
      "機会コスト",
      "納得の整理",
    ],
    oneLine: "特典が“後で単体で欲しくなる”ならセット、そうでなければ単品。",
    tags: [
      "セット",
      "特典",
      "比較",
    ],
  },
  {
    id: "gds_space_problem",
    title: "置き場所がもう限界だけど欲しい",
    example: "飾るスペース/収納が不足。",
    kind: "goods",
    mode: "long",
    chips: [
      "生活への影響",
      "後悔の原因になりやすい",
      "整理が必要",
    ],
    oneLine: "買うなら“何を手放すか”を先に決める。決められないなら保留/やめる。",
    tags: [
      "収納",
      "生活",
      "トレードオフ",
    ],
  },
  {
    id: "gds_subscription_box",
    title: "毎月の推しグッズ定期便を契約するか迷う",
    example: "続く支払いが不安。",
    kind: "goods",
    mode: "long",
    chips: [
      "継続コスト",
      "解約の手間",
      "長期判断",
    ],
    oneLine: "3ヶ月分の総額と満足を想定して、続かなそうなら単発にする。",
    tags: [
      "サブスク",
      "継続",
      "予算",
    ],
  },
  {
    id: "tkt_general_sale_5m",
    title: "一般販売、開始まであと5分",
    example: "買うか迷ってるのに時間がない。",
    kind: "ticket",
    mode: "short",
    chips: [
      "時間がない",
      "判断速度が優先",
      "まず仮判定",
    ],
    oneLine: "買うなら上限を決めて即決。迷うなら今回は見送り→次の機会に備える。",
    tags: [
      "一般",
      "開始直前",
      "即決",
    ],
  },
  {
    id: "tkt_same_day_decision",
    title: "当日券が出たけど迷う",
    example: "今日の予定は空いてる。",
    kind: "ticket",
    mode: "short",
    chips: [
      "今決める必要",
      "感情で揺れやすい",
      "最短でブレーキ",
    ],
    oneLine: "“行った後の自分”を想像してワクワクが勝つなら買う。",
    tags: [
      "当日券",
      "即時",
      "感情",
    ],
  },
  {
    id: "tkt_friend_waiting",
    title: "友達が今買うか待ってる",
    example: "返事を急かされてる。",
    kind: "ticket",
    mode: "short",
    chips: [
      "時間圧",
      "同調圧が入りやすい",
      "最低限整理",
    ],
    oneLine: "自分の上限とスケジュールだけ確認して返事する。",
    tags: [
      "同調圧",
      "即答",
      "友達",
    ],
  },
  {
    id: "tkt_lottery_deadline_today",
    title: "抽選応募、締切が今日。席種が2つで迷う",
    example: "S席とA席、価格差あり。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "時間は少ない",
      "重要ポイントは押さえる",
      "納得して応募",
    ],
    oneLine: "推し度と後悔リスクで席を決める。迷うなら安い方で参加を優先。",
    tags: [
      "抽選",
      "席種",
      "締切",
    ],
  },
  {
    id: "tkt_local_no_travel",
    title: "地元開催で遠征なし。価格は普通",
    example: "迷う理由は気持ちだけ。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "影響は中",
      "FOMOが鍵",
      "保留条件が作れる",
    ],
    oneLine: "申し込み前に“行かない場合の後悔”を1分だけ想像して比較。",
    tags: [
      "地元",
      "迷い",
      "気持ち",
    ],
  },
  {
    id: "tkt_two_days",
    title: "2日間公演、どっちか迷う",
    example: "仕事/学校と被りそう。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "比較が必要",
      "スケジュールが鍵",
      "中で十分",
    ],
    oneLine: "最悪の欠席リスクが低い日を選ぶ。",
    tags: [
      "日程",
      "比較",
      "リスク",
    ],
  },
  {
    id: "tkt_resale_available",
    title: "公式リセールがあるから焦りにくい",
    example: "買い逃してもチャンスがある。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "緊急度が下がる",
      "冷静に判断",
      "保留が有効",
    ],
    oneLine: "まず保留→リセール開始日に再診断する。",
    tags: [
      "リセール",
      "保留",
      "再検討",
    ],
  },
  {
    id: "tkt_travel_total_30k",
    title: "遠征＋宿泊あり、総額が3万円超えそう",
    example: "交通＋宿＋チケット。",
    kind: "ticket",
    mode: "long",
    chips: [
      "総額が大きい",
      "時間も消える",
      "生活への影響",
    ],
    oneLine: "翌月の固定費・休み・体力まで含めて判断。",
    tags: [
      "遠征",
      "宿泊",
      "高額",
    ],
  },
  {
    id: "tkt_multiple_seats",
    title: "席種が多い（3つ以上）＆価格差が大きい",
    example: "VIP/指定/見切れなど。",
    kind: "ticket",
    mode: "long",
    chips: [
      "選択肢が多い",
      "後悔しやすい",
      "比較が必要",
    ],
    oneLine: "優先は“体験”か“費用”かを決めてから席を選ぶ。",
    tags: [
      "席種",
      "比較",
      "体験",
    ],
  },
  {
    id: "tkt_group_trip_coordination",
    title: "同行者が複数、遠征計画もセット",
    example: "ホテルや移動の調整が必要。",
    kind: "ticket",
    mode: "long",
    chips: [
      "条件が多い",
      "調整コスト",
      "全体で判断",
    ],
    oneLine: "全員の上限と必須条件を先に揃える（合わなければ見送る）。",
    tags: [
      "同行",
      "調整",
      "計画",
    ],
  },
  {
    id: "tkt_festival_multi_days",
    title: "フェスで複数日券/単日券を迷う",
    example: "推し以外も出る。",
    kind: "ticket",
    mode: "long",
    chips: [
      "比較が複雑",
      "総額が膨らむ",
      "満足期待を整理",
    ],
    oneLine: "“推し以外も楽しめるか”で判断。楽しめないなら単日。",
    tags: [
      "フェス",
      "複数日",
      "総額",
    ],
  },
  {
    id: "tkt_time_off_risk",
    title: "休みが取れるか怪しいけど申し込みたい",
    example: "当たるとキャンセルが難しい。",
    kind: "ticket",
    mode: "long",
    chips: [
      "欠席リスク",
      "後悔ポイント",
      "長で整理",
    ],
    oneLine: "休みが取れない場合の損失（譲渡/リセール可否）を確認してから応募。",
    tags: [
      "欠席",
      "リスク",
      "抽選",
    ],
  },
  {
    id: "gds_ita_bag_supply",
    title: "痛バッグ用に同じ缶バッジを追加購入するか迷う",
    example: "もう少し数が欲しいが予算が心配。",
    kind: "goods",
    mode: "medium",
    chips: [
      "積み上げ出費",
      "満足は上がる",
      "上限設定が効く",
    ],
    oneLine: "完成ライン（必要個数）を決めて、それ以上はやめる。",
    tags: [
      "痛バ",
      "缶バ",
      "積み上げ",
    ],
  },
  {
    id: "gds_new_release_fomo",
    title: "新作発表直後でテンションMAX",
    example: "情報の熱に当てられてる。",
    kind: "goods",
    mode: "medium",
    chips: [
      "熱が高い",
      "判断が粗くなる",
      "冷却が効く",
    ],
    oneLine: "公式画像を保存して24時間だけ保留。まだ欲しければ中/長で再診断。",
    tags: [
      "新作",
      "テンション",
      "冷却",
    ],
  },
  {
    id: "gds_lottery_purchase_right",
    title: "購入権抽選に当たった（期限48時間）",
    example: "買える権利があるから迷う。",
    kind: "goods",
    mode: "medium",
    chips: [
      "期限あり",
      "希少性が強い",
      "納得して選ぶ",
    ],
    oneLine: "“当たったから買う”になってないか確認。欲しい理由が弱いなら保留。",
    tags: [
      "購入権",
      "抽選",
      "期限",
    ],
  },
  {
    id: "gds_preorder_split_payment",
    title: "予約で支払いが分割/後払い、実感が薄い",
    example: "つい高額に手を出しそう。",
    kind: "goods",
    mode: "long",
    chips: [
      "高額化しやすい",
      "実感が遅れる",
      "長で整理",
    ],
    oneLine: "総額を一括で見える化してから決める。",
    tags: [
      "分割",
      "後払い",
      "高額",
    ],
  },
  {
    id: "gds_multiple_preorders_overlap",
    title: "予約が重なって来月の出費が読めない",
    example: "複数の予約品が同月に来そう。",
    kind: "goods",
    mode: "long",
    chips: [
      "総額不明",
      "予算圧力",
      "整理が必要",
    ],
    oneLine: "“来月の推し活上限”を決め、超えるならどれかを保留/キャンセル。",
    tags: [
      "予約",
      "重なり",
      "予算",
    ],
  },
  {
    id: "tkt_abroad_streaming",
    title: "現地遠征か配信視聴か迷う",
    example: "価格差が大きい。",
    kind: "ticket",
    mode: "long",
    chips: [
      "選択肢の比較",
      "時間/費用差が大きい",
      "後悔ポイント整理",
    ],
    oneLine: "“現地でしか得られない価値”が明確なら遠征。曖昧なら配信。",
    tags: [
      "配信",
      "遠征",
      "比較",
    ],
  },
  {
    id: "tkt_last_minute_price_surge",
    title: "二次流通の価格が急騰して焦る",
    example: "相場に煽られてる。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "相場で焦りやすい",
      "後悔しやすい",
      "保留で冷却",
    ],
    oneLine: "上限を超えるならやめる。別日/配信/次回に切り替える。",
    tags: [
      "二次流通",
      "相場",
      "焦り",
    ],
  },
  {
    id: "tkt_bundle_goods_ticket",
    title: "チケット＋グッズ付き高額パックを迷う",
    example: "特典が魅力。",
    kind: "ticket",
    mode: "long",
    chips: [
      "総額が大きい",
      "価値の分解が必要",
      "後悔しやすい",
    ],
    oneLine: "特典単体の価値を見積もり、チケット価値と分けて考える。",
    tags: [
      "パック",
      "特典",
      "総額",
    ],
  },
  {
    id: "tkt_venue_visibility_tradeoff",
    title: "見切れ席/注釈席で安く行くか迷う",
    example: "体験の不確実性。",
    kind: "ticket",
    mode: "medium",
    chips: [
      "体験の差",
      "価格とのトレードオフ",
      "中で十分",
    ],
    oneLine: "体験の最低ライン（見えないと辛い等）を決めて判断。",
    tags: [
      "見切れ",
      "注釈",
      "トレードオフ",
    ],
  },
  {
    id: "tkt_parental_permission",
    title: "親の許可/お金の相談が必要",
    example: "決めてもすぐ動けない。",
    kind: "ticket",
    mode: "long",
    chips: [
      "条件が多い",
      "外部要因",
      "整理して相談",
    ],
    oneLine: "必要条件（お金/同伴/時間）をリスト化してから相談する。",
    tags: [
      "相談",
      "条件",
      "家族",
    ],
  },
];
